# Netlify configuration for Next.js SSR
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Optional: Enable pretty URLs
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
